var searchData=
[
  ['shapes_20or_20parameter_20sizes_20is_20not_20supported_0',['Certain operations, input shapes or parameter sizes is not supported',['../index.html#autotoc_md7',1,'']]],
  ['sizes_20is_20not_20supported_1',['Certain operations, input shapes or parameter sizes is not supported',['../index.html#autotoc_md7',1,'']]],
  ['softmax_2',['Softmax',['../group__Softmax.html',1,'']]],
  ['softmaxgraph_3',['SoftmaxGraph',['../classSoftmaxGraph.html',1,'']]],
  ['softmaxkernels_4',['SoftmaxKernels',['../group__SoftmaxKernels.html',1,'']]],
  ['softmaxmultiaxis_5',['SoftmaxMultiaxis',['../classSoftmaxMultiaxis.html',1,'']]],
  ['softmaxscalar_6',['SoftmaxScalar',['../classSoftmaxScalar.html',1,'']]],
  ['softmaxsingleaxis_7',['SoftmaxSingleaxis',['../classSoftmaxSingleaxis.html',1,'']]],
  ['split_8',['Split',['../group__Split.html',1,'']]],
  ['splitfilterfloatpktstream_9',['SplitFilterFloatPktStream',['../classSplitFilterFloatPktStream.html',1,'']]],
  ['splitfilterfloatstream_10',['SplitFilterFloatStream',['../classSplitFilterFloatStream.html',1,'']]],
  ['splitfilterfloatstreamtwice_11',['SplitFilterFloatStreamTwice',['../classSplitFilterFloatStreamTwice.html',1,'']]],
  ['splitfilterint8pktstream_12',['SplitFilterInt8PktStream',['../classSplitFilterInt8PktStream.html',1,'']]],
  ['splitfilterint8stream_13',['SplitFilterInt8Stream',['../classSplitFilterInt8Stream.html',1,'']]],
  ['splitfilterint8streamtwice_14',['SplitFilterInt8StreamTwice',['../classSplitFilterInt8StreamTwice.html',1,'']]],
  ['splitfilterpktstreamgraph_15',['SplitFilterPktStreamGraph',['../classSplitFilterPktStreamGraph.html',1,'']]],
  ['splitfilterpktstreamgraph_3c_20split_2c_20float_5ft_2c_20b_20_2ac_2c_20pad_5fh_20_2apad_5fw_2c_20hchunk_20_2apad_5fw_2c_20overlap_20_2apad_5fw_20_3e_16',['SplitFilterPktStreamGraph&lt; SPLIT, float_t, B *C, PAD_H *PAD_W, HCHUNK *PAD_W, OVERLAP *PAD_W &gt;',['../classSplitFilterPktStreamGraph.html',1,'']]],
  ['splitfilterpktstreamgraph_3c_20split_2c_20tt_2c_20b_2c_20c_20_2apad_5fh_20_2apad_5fw_2c_20cchunk_20_2apad_5fh_20_2apad_5fw_2c_200_20_3e_17',['SplitFilterPktStreamGraph&lt; SPLIT, TT, B, C *PAD_H *PAD_W, CCHUNK *PAD_H *PAD_W, 0 &gt;',['../classSplitFilterPktStreamGraph.html',1,'']]],
  ['splitfilterpktstreamgraph_3c_20split_2c_20tt_2c_20b_2c_20h_20_2aw_20_2ac_2c_20hchunk_20_2aw_20_2ac_2c_200_20_3e_18',['SplitFilterPktStreamGraph&lt; SPLIT, TT, B, H *W *C, HCHUNK *W *C, 0 &gt;',['../classSplitFilterPktStreamGraph.html',1,'']]],
  ['splitfilterpktstreamgraph_3c_20splitfilterfloatpktstream_2c_20float_2c_201_2c_20inp_5fh_20_2ainp_5fw_2c_20hchunk_20_2ainp_5fw_2c_200_20_3e_19',['SplitFilterPktStreamGraph&lt; SplitFilterFloatPktStream, float, 1, INP_H *INP_W, HCHUNK *INP_W, 0 &gt;',['../classSplitFilterPktStreamGraph.html',1,'']]],
  ['splitfilterpktstreamgraph_3c_20splitfilterint8pktstream_2c_20tt_2c_20b_20_2ac_2c_20pad_5fh_20_2apad_5fw_2c_20hchunk_20_2apad_5fw_2c_20overlap_20_2apad_5fw_20_3e_20',['SplitFilterPktStreamGraph&lt; SplitFilterInt8PktStream, TT, B *C, PAD_H *PAD_W, HCHUNK *PAD_W, OVERLAP *PAD_W &gt;',['../classSplitFilterPktStreamGraph.html',1,'']]],
  ['splitfilterpktstreamgraph_3c_20splitfilterint8pktstream_2c_20tt_2c_20b_2c_20c_20_2apad_5fh_20_2apad_5fw_2c_20cchunk_20_2apad_5fh_20_2apad_5fw_2c_200_20_3e_21',['SplitFilterPktStreamGraph&lt; SplitFilterInt8PktStream, TT, B, C *PAD_H *PAD_W, CCHUNK *PAD_H *PAD_W, 0 &gt;',['../classSplitFilterPktStreamGraph.html',1,'']]],
  ['splitfilterstreamgraph_22',['SplitFilterStreamGraph',['../classSplitFilterStreamGraph.html',1,'']]],
  ['splitfilterstreamtwicegraph_23',['SplitFilterStreamTwiceGraph',['../classSplitFilterStreamTwiceGraph.html',1,'']]],
  ['splitgraph_24',['SplitGraph',['../classSplitGraph.html',1,'']]],
  ['splitgraph_3c_20split_2c_20float_5ft_2c_20b_20_2ac_2c_20pad_5fh_20_2apad_5fw_2c_20hchunk_20_2apad_5fw_2c_20overlap_20_2apad_5fw_20_3e_25',['SplitGraph&lt; SPLIT, float_t, B *C, PAD_H *PAD_W, HCHUNK *PAD_W, OVERLAP *PAD_W &gt;',['../classSplitGraph.html',1,'']]],
  ['splitgraph_3c_20splitint8_2c_20tt_2c_20b_20_2ac_2c_20pad_5fh_20_2apad_5fw_2c_20hchunk_20_2apad_5fw_2c_20overlap_20_2apad_5fw_20_3e_26',['SplitGraph&lt; SplitInt8, TT, B *C, PAD_H *PAD_W, HCHUNK *PAD_W, OVERLAP *PAD_W &gt;',['../classSplitGraph.html',1,'']]],
  ['splitint8_27',['SplitInt8',['../classSplitInt8.html',1,'']]],
  ['splitkernels_28',['SplitKernels',['../group__SplitKernels.html',1,'']]],
  ['splitscalar_29',['SplitScalar',['../classSplitScalar.html',1,'']]],
  ['splittwo32bitstreams_30',['SplitTwo32bitStreams',['../classSplitTwo32bitStreams.html',1,'']]],
  ['splittwostreamgraph_31',['SplitTwoStreamGraph',['../classSplitTwoStreamGraph.html',1,'']]],
  ['supported_32',['Certain operations, input shapes or parameter sizes is not supported',['../index.html#autotoc_md7',1,'']]]
];
