var searchData=
[
  ['qemu_0',['Functional/performance check: runs system in hardware emulation with QEMU',['../md_lenet__example.html#autotoc_md23',1,'']]],
  ['qgemm_1',['qgemm',['../classQgemm.html',1,'Qgemm&lt; TT, TTPARAM, M, K, N &gt;'],['../group__Qgemm.html',1,'Qgemm']]],
  ['qgemmchunkngraph_2',['QgemmChunkNGraph',['../classQgemmChunkNGraph.html',1,'']]],
  ['qgemmgraph_3',['QgemmGraph',['../classQgemmGraph.html',1,'']]],
  ['qgemmkernels_4',['QgemmKernels',['../group__QgemmKernels.html',1,'']]],
  ['qgemmscalar_5',['QgemmScalar',['../classQgemmScalar.html',1,'']]],
  ['qgemmstream_6',['QgemmStream',['../classQgemmStream.html',1,'']]],
  ['qgemmstreamgraph_7',['QgemmStreamGraph',['../classQgemmStreamGraph.html',1,'']]],
  ['qlinearadd_8',['QLinearAdd',['../group__QLinearAdd.html',1,'']]],
  ['qlinearaddgraph_9',['QLinearAddGraph',['../classQLinearAddGraph.html',1,'']]],
  ['qlinearaddint8_10',['QLinearAddInt8',['../classQLinearAddInt8.html',1,'']]],
  ['qlinearaddkernels_11',['QLinearAddKernels',['../group__QLinearAddKernels.html',1,'']]],
  ['qlinearavgpoolscalarbchw_12',['QLinearAvgpoolScalarBCHW',['../classQLinearAvgpoolScalarBCHW.html',1,'']]],
  ['qlinearconv_13',['QLinearConv',['../group__QLinearConv.html',1,'']]],
  ['qlinearconv1x1pktstream_14',['QLinearConv1x1PktStream',['../classQLinearConv1x1PktStream.html',1,'']]],
  ['qlinearconv1x1stream_15',['QLinearConv1x1Stream',['../classQLinearConv1x1Stream.html',1,'']]],
  ['qlinearconv3x3_16',['QLinearConv3x3',['../classQLinearConv3x3.html',1,'']]],
  ['qlinearconv5x5_17',['QLinearConv5x5',['../classQLinearConv5x5.html',1,'']]],
  ['qlinearconv5x5scale32bit_18',['QLinearConv5x5Scale32bit',['../classQLinearConv5x5Scale32bit.html',1,'']]],
  ['qlinearconvchunkhgraph_19',['QLinearConvChunkHGraph',['../classQLinearConvChunkHGraph.html',1,'']]],
  ['qlinearconvchunkhpktstreamgraph_20',['QLinearConvChunkHPktStreamGraph',['../classQLinearConvChunkHPktStreamGraph.html',1,'']]],
  ['qlinearconvchunkhstreamgraph_21',['QLinearConvChunkHStreamGraph',['../classQLinearConvChunkHStreamGraph.html',1,'']]],
  ['qlinearconvgraph_22',['QLinearConvGraph',['../classQLinearConvGraph.html',1,'']]],
  ['qlinearconvhx4pktstream_23',['QLinearConvHx4PktStream',['../classQLinearConvHx4PktStream.html',1,'']]],
  ['qlinearconvhx4stream_24',['QLinearConvHx4Stream',['../classQLinearConvHx4Stream.html',1,'']]],
  ['qlinearconvhx4streamscale32bit_25',['QLinearConvHx4StreamScale32bit',['../classQLinearConvHx4StreamScale32bit.html',1,'']]],
  ['qlinearconvhx6x8bitstream_26',['qlinearconvhx6x8bitstream',['../classQLinearConvHx6x8bitStream.html',1,'QLinearConvHx6x8bitStream&lt; TT, TTPARAM, INP_H, INP_W, OUT_W, OUT_W_PAD, STEP_H, STEP_W, B, C, M, KH, KW, GROUP &gt;'],['../classQLinearConvHx6x8bitStream.html#abbce0d4d7db2a0608a624d4c39eec9ec',1,'QLinearConvHx6x8bitStream::QLinearConvHx6x8bitStream()']]],
  ['qlinearconvkernels_27',['QLinearConvKernels',['../group__QLinearConvKernels.html',1,'']]],
  ['qlinearconvscalar_28',['QLinearConvScalar',['../classQLinearConvScalar.html',1,'']]],
  ['qlinearconvscalarstream_29',['QLinearConvScalarStream',['../classQLinearConvScalarStream.html',1,'']]],
  ['qlinearconvstreamgraph_30',['QLinearConvStreamGraph',['../classQLinearConvStreamGraph.html',1,'']]],
  ['qlinearmac_31',['qlinearmac',['../classQlinearMac.html',1,'QlinearMac&lt; TT, TTPARAM, B, W, IS_RELU &gt;'],['../group__QlinearMac.html',1,'QlinearMac']]],
  ['qlinearmacgraph_32',['QlinearMacGraph',['../classQlinearMacGraph.html',1,'']]],
  ['qlinearmackernels_33',['QlinearMacKernels',['../group__QlinearMacKernels.html',1,'']]],
  ['qlinearmacscalar_34',['QlinearMacScalar',['../classQlinearMacScalar.html',1,'']]],
  ['qlinearmacstreamgraph_35',['QlinearMacStreamGraph',['../classQlinearMacStreamGraph.html',1,'']]],
  ['qlinearpool2d_36',['QLinearPool2D',['../group__QLinearPool2D.html',1,'']]],
  ['qlinearpoolchunkcstreamgraph_37',['QLinearPoolChunkCStreamGraph',['../classQLinearPoolChunkCStreamGraph.html',1,'']]],
  ['qlinearpoolstreamgraph_38',['QLinearPoolStreamGraph',['../classQLinearPoolStreamGraph.html',1,'']]],
  ['qlinearsoftmax_39',['QLinearSoftmax',['../group__QLinearSoftmax.html',1,'']]],
  ['qlinearsoftmaxfloatmul_40',['QLinearSoftmaxFloatmul',['../classQLinearSoftmaxFloatmul.html',1,'']]],
  ['qlinearsoftmaxkernels_41',['QLinearSoftmaxKernels',['../group__QLinearSoftmaxKernels.html',1,'']]],
  ['qlinearsoftmaxscalar_42',['QLinearSoftmaxScalar',['../classQLinearSoftmaxScalar.html',1,'']]],
  ['qlinearsoftmaxsingleaxis_43',['QLinearSoftmaxSingleaxis',['../classQLinearSoftmaxSingleaxis.html',1,'']]],
  ['qlinearsoftmaxstreamgraph_44',['QLinearSoftmaxStreamGraph',['../classQLinearSoftmaxStreamGraph.html',1,'']]],
  ['quantize_20the_20model_20optional_45',['Quantize the model (optional)',['../md_lenet__example.html#autotoc_md15',1,'']]],
  ['quantizelinear_46',['quantizelinear',['../classQuantizeLinear.html',1,'QuantizeLinear&lt; TT, INP_H, INP_W, OUT_W &gt;'],['../group__QuantizeLinear.html',1,'QuantizeLinear']]],
  ['quantizelinearchunkhpktstreamgraph_47',['QuantizeLinearChunkHPktStreamGraph',['../classQuantizeLinearChunkHPktStreamGraph.html',1,'']]],
  ['quantizelinearfmul_48',['QuantizeLinearFmul',['../classQuantizeLinearFmul.html',1,'']]],
  ['quantizelinearfmulstream_49',['QuantizeLinearFmulStream',['../classQuantizeLinearFmulStream.html',1,'']]],
  ['quantizelineargraph_50',['QuantizeLinearGraph',['../classQuantizeLinearGraph.html',1,'']]],
  ['quantizelinearkernels_51',['QuantizeLinearKernels',['../group__QuantizeLinearKernels.html',1,'']]],
  ['quantizelinearscalar_52',['QuantizeLinearScalar',['../classQuantizeLinearScalar.html',1,'']]],
  ['quantizelinearstreamgraph_53',['QuantizeLinearStreamGraph',['../classQuantizeLinearStreamGraph.html',1,'']]]
];
