var searchData=
[
  ['qemu_0',['Functional/performance check: runs system in hardware emulation with QEMU',['../md_lenet__example.html#autotoc_md23',1,'']]],
  ['qgemm_1',['qgemm',['../classQgemm.html',1,'Qgemm&lt; TT, TTPARAM, M, K, N &gt;'],['../group__Qgemm.html',1,'Qgemm']]],
  ['qgemmchunkngraph_2',['QgemmChunkNGraph',['../classQgemmChunkNGraph.html',1,'']]],
  ['qgemmgraph_3',['QgemmGraph',['../classQgemmGraph.html',1,'']]],
  ['qgemmkernels_4',['QgemmKernels',['../group__QgemmKernels.html',1,'']]],
  ['qgemmscalar_5',['QgemmScalar',['../classQgemmScalar.html',1,'']]],
  ['qgemmstream_6',['QgemmStream',['../classQgemmStream.html',1,'']]],
  ['qgemmstreamgraph_7',['QgemmStreamGraph',['../classQgemmStreamGraph.html',1,'']]],
  ['qlinearadd_8',['QLinearAdd',['../group__QLinearAdd.html',1,'']]],
  ['qlinearaddgraph_9',['QLinearAddGraph',['../classQLinearAddGraph.html',1,'']]],
  ['qlinearaddint8_10',['QLinearAddInt8',['../classQLinearAddInt8.html',1,'']]],
  ['qlinearaddkernels_11',['QLinearAddKernels',['../group__QLinearAddKernels.html',1,'']]],
  ['qlinearavgpoolscalarbchw_12',['QLinearAvgpoolScalarBCHW',['../classQLinearAvgpoolScalarBCHW.html',1,'']]],
  ['qlinearconv_13',['QLinearConv',['../group__QLinearConv.html',1,'']]],
  ['qlinearconv1x1pktstream_14',['QLinearConv1x1PktStream',['../classQLinearConv1x1PktStream.html',1,'']]],
  ['qlinearconv1x1stream_15',['QLinearConv1x1Stream',['../classQLinearConv1x1Stream.html',1,'']]],
  ['qlinearconv3x3_16',['QLinearConv3x3',['../classQLinearConv3x3.html',1,'']]],
  ['qlinearconv5x5_17',['QLinearConv5x5',['../classQLinearConv5x5.html',1,'']]],
  ['qlinearconv5x5scale32bit_18',['QLinearConv5x5Scale32bit',['../classQLinearConv5x5Scale32bit.html',1,'']]],
  ['qlinearconvchunkcgraph_19',['QLinearConvChunkCGraph',['../classQLinearConvChunkCGraph.html',1,'']]],
  ['qlinearconvchunkhgraph_20',['QLinearConvChunkHGraph',['../classQLinearConvChunkHGraph.html',1,'']]],
  ['qlinearconvchunkhpktstreamgraph_21',['QLinearConvChunkHPktStreamGraph',['../classQLinearConvChunkHPktStreamGraph.html',1,'']]],
  ['qlinearconvchunkhstreamgraph_22',['QLinearConvChunkHStreamGraph',['../classQLinearConvChunkHStreamGraph.html',1,'']]],
  ['qlinearconvgraph_23',['QLinearConvGraph',['../classQLinearConvGraph.html',1,'']]],
  ['qlinearconvhx4pktstream_24',['QLinearConvHx4PktStream',['../classQLinearConvHx4PktStream.html',1,'']]],
  ['qlinearconvhx4stream_25',['QLinearConvHx4Stream',['../classQLinearConvHx4Stream.html',1,'']]],
  ['qlinearconvhx4streamscale32bit_26',['QLinearConvHx4StreamScale32bit',['../classQLinearConvHx4StreamScale32bit.html',1,'']]],
  ['qlinearconvhx6x8bitstream_27',['qlinearconvhx6x8bitstream',['../classQLinearConvHx6x8bitStream.html',1,'QLinearConvHx6x8bitStream&lt; TT, TTPARAM, INP_H, INP_W, OUT_W, OUT_W_PAD, STEP_H, STEP_W, B, C, M, KH, KW, GROUP &gt;'],['../classQLinearConvHx6x8bitStream.html#abbce0d4d7db2a0608a624d4c39eec9ec',1,'QLinearConvHx6x8bitStream::QLinearConvHx6x8bitStream()']]],
  ['qlinearconvkernels_28',['QLinearConvKernels',['../group__QLinearConvKernels.html',1,'']]],
  ['qlinearconvscalar_29',['QLinearConvScalar',['../classQLinearConvScalar.html',1,'']]],
  ['qlinearconvscalarstream_30',['QLinearConvScalarStream',['../classQLinearConvScalarStream.html',1,'']]],
  ['qlinearconvstreamgraph_31',['QLinearConvStreamGraph',['../classQLinearConvStreamGraph.html',1,'']]],
  ['qlinearglobalavgpoolscalarbchw_32',['QLinearGlobalAvgpoolScalarBCHW',['../classQLinearGlobalAvgpoolScalarBCHW.html',1,'']]],
  ['qlinearmac_33',['qlinearmac',['../classQlinearMac.html',1,'QlinearMac&lt; TT, TTPARAM, B, W, IS_RELU &gt;'],['../group__QlinearMac.html',1,'QlinearMac']]],
  ['qlinearmacgraph_34',['QlinearMacGraph',['../classQlinearMacGraph.html',1,'']]],
  ['qlinearmackernels_35',['QlinearMacKernels',['../group__QlinearMacKernels.html',1,'']]],
  ['qlinearmacscalar_36',['QlinearMacScalar',['../classQlinearMacScalar.html',1,'']]],
  ['qlinearmacstreamgraph_37',['QlinearMacStreamGraph',['../classQlinearMacStreamGraph.html',1,'']]],
  ['qlinearpool2d_38',['QLinearPool2D',['../group__QLinearPool2D.html',1,'']]],
  ['qlinearpoolchunkcgraph_39',['QLinearPoolChunkCGraph',['../classQLinearPoolChunkCGraph.html',1,'']]],
  ['qlinearpoolgraph_40',['QLinearPoolGraph',['../classQLinearPoolGraph.html',1,'']]],
  ['qlinearpoolstreamgraph_41',['QLinearPoolStreamGraph',['../classQLinearPoolStreamGraph.html',1,'']]],
  ['qlinearsoftmax_42',['QLinearSoftmax',['../group__QLinearSoftmax.html',1,'']]],
  ['qlinearsoftmaxfloatmul_43',['QLinearSoftmaxFloatmul',['../classQLinearSoftmaxFloatmul.html',1,'']]],
  ['qlinearsoftmaxkernels_44',['QLinearSoftmaxKernels',['../group__QLinearSoftmaxKernels.html',1,'']]],
  ['qlinearsoftmaxscalar_45',['QLinearSoftmaxScalar',['../classQLinearSoftmaxScalar.html',1,'']]],
  ['qlinearsoftmaxsingleaxis_46',['QLinearSoftmaxSingleaxis',['../classQLinearSoftmaxSingleaxis.html',1,'']]],
  ['qlinearsoftmaxstreamgraph_47',['QLinearSoftmaxStreamGraph',['../classQLinearSoftmaxStreamGraph.html',1,'']]],
  ['quantize_20the_20model_20optional_48',['Quantize the model (optional)',['../md_lenet__example.html#autotoc_md15',1,'']]],
  ['quantizelinear_49',['quantizelinear',['../group__QuantizeLinear.html',1,'QuantizeLinear'],['../classQuantizeLinear.html',1,'QuantizeLinear&lt; TT, INP_H, INP_W, OUT_W &gt;']]],
  ['quantizelinearchunkhpktstreamgraph_50',['QuantizeLinearChunkHPktStreamGraph',['../classQuantizeLinearChunkHPktStreamGraph.html',1,'']]],
  ['quantizelinearfmul_51',['QuantizeLinearFmul',['../classQuantizeLinearFmul.html',1,'']]],
  ['quantizelinearfmulstream_52',['QuantizeLinearFmulStream',['../classQuantizeLinearFmulStream.html',1,'']]],
  ['quantizelineargraph_53',['QuantizeLinearGraph',['../classQuantizeLinearGraph.html',1,'']]],
  ['quantizelinearkernels_54',['QuantizeLinearKernels',['../group__QuantizeLinearKernels.html',1,'']]],
  ['quantizelinearscalar_55',['QuantizeLinearScalar',['../classQuantizeLinearScalar.html',1,'']]],
  ['quantizelinearstreamgraph_56',['QuantizeLinearStreamGraph',['../classQuantizeLinearStreamGraph.html',1,'']]]
];
