var searchData=
[
  ['check_3a_20runs_20graph_20in_20aiesimulator_0',['Functional/performance check: runs graph in aiesimulator',['../md_lenet__example.html#autotoc_md22',1,'']]],
  ['check_3a_20runs_20graph_20in_20x86simulator_1',['Functional check: runs graph in x86simulator',['../md_lenet__example.html#autotoc_md20',1,'']]],
  ['check_3a_20runs_20system_20in_20hardware_20emulation_20with_20qemu_2',['Functional/performance check: runs system in hardware emulation with QEMU',['../md_lenet__example.html#autotoc_md23',1,'']]],
  ['check_3a_20runs_20system_20software_20emulation_3',['Functional check: runs system software emulation',['../md_lenet__example.html#autotoc_md21',1,'']]],
  ['closed_20division_20mlperf_20pretrained_4',['MLPerf Closed Division (MLPerf pretrained)',['../md_profile.html#autotoc_md27',1,'']]],
  ['concat_5',['Concat',['../group__Concat.html',1,'']]],
  ['concatfloat_6',['ConcatFloat',['../classConcatFloat.html',1,'']]],
  ['concatfloatpktstream_7',['ConcatFloatPktStream',['../classConcatFloatPktStream.html',1,'']]],
  ['concatfloatstream_8',['ConcatFloatStream',['../classConcatFloatStream.html',1,'']]],
  ['concatfloatstreamsequentially_9',['ConcatFloatStreamSequentially',['../classConcatFloatStreamSequentially.html',1,'']]],
  ['concatfloatstreamwithstall_10',['ConcatFloatStreamWithStall',['../classConcatFloatStreamWithStall.html',1,'']]],
  ['concatgraph_11',['ConcatGraph',['../classConcatGraph.html',1,'']]],
  ['concatgraph_3c_20concat_2c_20float_5ft_2c_20chunk_5fcount_2c_201_2c_20nchunk_2c_20n_20_3e_12',['ConcatGraph&lt; CONCAT, float_t, CHUNK_COUNT, 1, NCHUNK, N &gt;',['../classConcatGraph.html',1,'']]],
  ['concatgraph_3c_20concat_2c_20float_5ft_2c_20chunk_5fcount_2c_20concat_5fh_2c_20concat_5fw_2c_20concat_5fblock_20_3e_13',['ConcatGraph&lt; CONCAT, float_t, CHUNK_COUNT, CONCAT_H, CONCAT_W, CONCAT_BLOCK &gt;',['../classConcatGraph.html',1,'']]],
  ['concatint8_14',['ConcatInt8',['../classConcatInt8.html',1,'']]],
  ['concatint8stream_15',['ConcatInt8Stream',['../classConcatInt8Stream.html',1,'']]],
  ['concatkernels_16',['ConcatKernels',['../group__ConcatKernels.html',1,'']]],
  ['concatscalar_17',['ConcatScalar',['../classConcatScalar.html',1,'']]],
  ['concattwo32bitstreams_18',['ConcatTwo32bitStreams',['../classConcatTwo32bitStreams.html',1,'']]],
  ['concattwostreamgraph_19',['ConcatTwoStreamGraph',['../classConcatTwoStreamGraph.html',1,'']]],
  ['conv1x1out4relustream_20',['Conv1x1Out4ReluStream',['../classConv1x1Out4ReluStream.html',1,'']]],
  ['conv1x1relu_21',['Conv1x1Relu',['../classConv1x1Relu.html',1,'']]],
  ['conv1x1relupktstream_22',['Conv1x1ReluPktStream',['../classConv1x1ReluPktStream.html',1,'']]],
  ['conv1x1relustream_23',['Conv1x1ReluStream',['../classConv1x1ReluStream.html',1,'']]],
  ['conv2d_24',['Conv2D',['../group__Conv2D.html',1,'']]],
  ['conv2dkernels_25',['Conv2DKernels',['../group__Conv2DKernels.html',1,'']]],
  ['conv5x5on8relu_26',['Conv5x5on8Relu',['../classConv5x5on8Relu.html',1,'']]],
  ['convhx4out4relustream_27',['ConvHx4Out4ReluStream',['../classConvHx4Out4ReluStream.html',1,'']]],
  ['convhx4relu_28',['ConvHx4Relu',['../classConvHx4Relu.html',1,'']]],
  ['convhx4relupktstream_29',['ConvHx4ReluPktStream',['../classConvHx4ReluPktStream.html',1,'']]],
  ['convhx4relustream_30',['ConvHx4ReluStream',['../classConvHx4ReluStream.html',1,'']]],
  ['convhx4relustreammultirow_31',['ConvHx4ReluStreamMultiRow',['../classConvHx4ReluStreamMultiRow.html',1,'']]],
  ['convhx8relustream_32',['ConvHx8ReluStream',['../classConvHx8ReluStream.html',1,'']]],
  ['convreluchunkhgraph_33',['ConvReluChunkHGraph',['../classConvReluChunkHGraph.html',1,'']]],
  ['convreluchunkhpktstreamgraph_34',['ConvReluChunkHPktStreamGraph',['../classConvReluChunkHPktStreamGraph.html',1,'']]],
  ['convreluchunkhstreamgraph_35',['ConvReluChunkHStreamGraph',['../classConvReluChunkHStreamGraph.html',1,'']]],
  ['convreluchunkmgraph_36',['ConvReluChunkMGraph',['../classConvReluChunkMGraph.html',1,'']]],
  ['convrelugraph_37',['ConvReluGraph',['../classConvReluGraph.html',1,'']]],
  ['convreluscalar_38',['ConvReluScalar',['../classConvReluScalar.html',1,'']]],
  ['convreluscalarstream_39',['ConvReluScalarStream',['../classConvReluScalarStream.html',1,'']]],
  ['convrelustreamgraph_40',['ConvReluStreamGraph',['../classConvReluStreamGraph.html',1,'']]]
];
