var searchData=
[
  ['qemu_0',['Functional/performance check: runs system in hardware emulation with QEMU',['../md_lenet__example.html#autotoc_md23',1,'']]],
  ['qgemm_1',['qgemm',['../classQgemm.html',1,'Qgemm&lt; TT, TTPARAM, M, K, N &gt;'],['../group__Qgemm.html',1,'Qgemm']]],
  ['qgemmchunkngraph_2',['QgemmChunkNGraph',['../classQgemmChunkNGraph.html',1,'']]],
  ['qgemmgraph_3',['QgemmGraph',['../classQgemmGraph.html',1,'']]],
  ['qgemmkernels_4',['QgemmKernels',['../group__QgemmKernels.html',1,'']]],
  ['qgemmscalar_5',['QgemmScalar',['../classQgemmScalar.html',1,'']]],
  ['qgemmstream_6',['QgemmStream',['../classQgemmStream.html',1,'']]],
  ['qgemmstreamgraph_7',['QgemmStreamGraph',['../classQgemmStreamGraph.html',1,'']]],
  ['qlinearadd_8',['QLinearAdd',['../group__QLinearAdd.html',1,'']]],
  ['qlinearaddgraph_9',['QLinearAddGraph',['../classQLinearAddGraph.html',1,'']]],
  ['qlinearaddint8_10',['QLinearAddInt8',['../classQLinearAddInt8.html',1,'']]],
  ['qlinearaddkernels_11',['QLinearAddKernels',['../group__QLinearAddKernels.html',1,'']]],
  ['qlinearavgpoolscalarbchw_12',['QLinearAvgpoolScalarBCHW',['../classQLinearAvgpoolScalarBCHW.html',1,'']]],
  ['qlinearconv_13',['QLinearConv',['../group__QLinearConv.html',1,'']]],
  ['qlinearconv1x1inputpackets_14',['QLinearConv1x1InputPackets',['../classQLinearConv1x1InputPackets.html',1,'']]],
  ['qlinearconv1x1stream_15',['QLinearConv1x1Stream',['../classQLinearConv1x1Stream.html',1,'']]],
  ['qlinearconv1x1streaminputpackets_16',['QLinearConv1x1StreamInputPackets',['../classQLinearConv1x1StreamInputPackets.html',1,'']]],
  ['qlinearconv3x3_17',['QLinearConv3x3',['../classQLinearConv3x3.html',1,'']]],
  ['qlinearconv5x5_18',['QLinearConv5x5',['../classQLinearConv5x5.html',1,'']]],
  ['qlinearconv5x5scale32bit_19',['QLinearConv5x5Scale32bit',['../classQLinearConv5x5Scale32bit.html',1,'']]],
  ['qlinearconvchunkcgraph_20',['QLinearConvChunkCGraph',['../classQLinearConvChunkCGraph.html',1,'']]],
  ['qlinearconvchunkhgraph_21',['QLinearConvChunkHGraph',['../classQLinearConvChunkHGraph.html',1,'']]],
  ['qlinearconvchunkhpktstreamgraph_22',['QLinearConvChunkHPktStreamGraph',['../classQLinearConvChunkHPktStreamGraph.html',1,'']]],
  ['qlinearconvchunkhstreamgraph_23',['QLinearConvChunkHStreamGraph',['../classQLinearConvChunkHStreamGraph.html',1,'']]],
  ['qlinearconvgraph_24',['QLinearConvGraph',['../classQLinearConvGraph.html',1,'']]],
  ['qlinearconvhx4pktstream_25',['QLinearConvHx4PktStream',['../classQLinearConvHx4PktStream.html',1,'']]],
  ['qlinearconvhx4stream_26',['QLinearConvHx4Stream',['../classQLinearConvHx4Stream.html',1,'']]],
  ['qlinearconvhx4streamscale32bit_27',['QLinearConvHx4StreamScale32bit',['../classQLinearConvHx4StreamScale32bit.html',1,'']]],
  ['qlinearconvhx6x8bitstream_28',['qlinearconvhx6x8bitstream',['../classQLinearConvHx6x8bitStream.html',1,'QLinearConvHx6x8bitStream&lt; TT, TTPARAM, INP_H, INP_W, OUT_W, OUT_W_PAD, STEP_H, STEP_W, B, C, M, KH, KW, GROUP &gt;'],['../classQLinearConvHx6x8bitStream.html#abbce0d4d7db2a0608a624d4c39eec9ec',1,'QLinearConvHx6x8bitStream::QLinearConvHx6x8bitStream()']]],
  ['qlinearconvhx8_29',['QLinearConvHx8',['../classQLinearConvHx8.html',1,'']]],
  ['qlinearconvhx8pktstream_30',['QLinearConvHx8PktStream',['../classQLinearConvHx8PktStream.html',1,'']]],
  ['qlinearconvkernels_31',['QLinearConvKernels',['../group__QLinearConvKernels.html',1,'']]],
  ['qlinearconvscalar_32',['QLinearConvScalar',['../classQLinearConvScalar.html',1,'']]],
  ['qlinearconvscalarstream_33',['QLinearConvScalarStream',['../classQLinearConvScalarStream.html',1,'']]],
  ['qlinearconvstreamgraph_34',['QLinearConvStreamGraph',['../classQLinearConvStreamGraph.html',1,'']]],
  ['qlinearglobalavgpoolscalarbchw_35',['QLinearGlobalAvgpoolScalarBCHW',['../classQLinearGlobalAvgpoolScalarBCHW.html',1,'']]],
  ['qlinearmac_36',['qlinearmac',['../classQlinearMac.html',1,'QlinearMac&lt; TT, TTPARAM, B, W, IS_RELU &gt;'],['../group__QlinearMac.html',1,'QlinearMac']]],
  ['qlinearmacgraph_37',['QlinearMacGraph',['../classQlinearMacGraph.html',1,'']]],
  ['qlinearmackernels_38',['QlinearMacKernels',['../group__QlinearMacKernels.html',1,'']]],
  ['qlinearmacscalar_39',['QlinearMacScalar',['../classQlinearMacScalar.html',1,'']]],
  ['qlinearmacstreamgraph_40',['QlinearMacStreamGraph',['../classQlinearMacStreamGraph.html',1,'']]],
  ['qlinearpool2d_41',['QLinearPool2D',['../group__QLinearPool2D.html',1,'']]],
  ['qlinearpoolchunkcgraph_42',['QLinearPoolChunkCGraph',['../classQLinearPoolChunkCGraph.html',1,'']]],
  ['qlinearpoolgraph_43',['QLinearPoolGraph',['../classQLinearPoolGraph.html',1,'']]],
  ['qlinearpoolstreamgraph_44',['QLinearPoolStreamGraph',['../classQLinearPoolStreamGraph.html',1,'']]],
  ['qlinearsoftmax_45',['QLinearSoftmax',['../group__QLinearSoftmax.html',1,'']]],
  ['qlinearsoftmaxfloatmul_46',['QLinearSoftmaxFloatmul',['../classQLinearSoftmaxFloatmul.html',1,'']]],
  ['qlinearsoftmaxkernels_47',['QLinearSoftmaxKernels',['../group__QLinearSoftmaxKernels.html',1,'']]],
  ['qlinearsoftmaxscalar_48',['QLinearSoftmaxScalar',['../classQLinearSoftmaxScalar.html',1,'']]],
  ['qlinearsoftmaxsingleaxis_49',['QLinearSoftmaxSingleaxis',['../classQLinearSoftmaxSingleaxis.html',1,'']]],
  ['qlinearsoftmaxstreamgraph_50',['QLinearSoftmaxStreamGraph',['../classQLinearSoftmaxStreamGraph.html',1,'']]],
  ['quantize_20the_20model_20optional_51',['Quantize the model (optional)',['../md_lenet__example.html#autotoc_md15',1,'']]],
  ['quantizelinear_52',['quantizelinear',['../classQuantizeLinear.html',1,'QuantizeLinear&lt; TT, INP_H, INP_W, OUT_W &gt;'],['../group__QuantizeLinear.html',1,'QuantizeLinear']]],
  ['quantizelinearchunkhpktstreamgraph_53',['QuantizeLinearChunkHPktStreamGraph',['../classQuantizeLinearChunkHPktStreamGraph.html',1,'']]],
  ['quantizelinearfmul_54',['QuantizeLinearFmul',['../classQuantizeLinearFmul.html',1,'']]],
  ['quantizelinearfmulstream_55',['QuantizeLinearFmulStream',['../classQuantizeLinearFmulStream.html',1,'']]],
  ['quantizelineargraph_56',['QuantizeLinearGraph',['../classQuantizeLinearGraph.html',1,'']]],
  ['quantizelinearkernels_57',['QuantizeLinearKernels',['../group__QuantizeLinearKernels.html',1,'']]],
  ['quantizelinearscalar_58',['QuantizeLinearScalar',['../classQuantizeLinearScalar.html',1,'']]],
  ['quantizelinearstreamgraph_59',['QuantizeLinearStreamGraph',['../classQuantizeLinearStreamGraph.html',1,'']]]
];
